import { ProductData } from './types';

import {
  burtonFreeThinkerImg1,
  burtonFreeThinkerImg2,
  burtonFreeThinkerImg3,
  burtonBlossomImg1,
  burtonBlossomImg2,
  burtonBlossomImg3,
  burtonFamilyImg1,
  burtonFamilyImg2,
  burtonFamilyImg3,
  burtonCustomImg1,
  burtonCustomImg2,
  burtonCustomImg3,
  burtonInstigatorImg1,
  burtonInstigatorImg2,
  burtonInstigatorImg3,
  nitroPrimeImg1,
  nitroPrimeImg2,
  nitroPrimeImg3,
  nitroPrimeRawImg1,
  nitroPrimeRawImg2,
  nitroPrimeRawImg3,
  nitroDropImg1,
  nitroDropImg2,
  nitroDropImg3,
  nitroCheapImg1,
  nitroCheapImg2,
  nitroCheapImg3,
  nitroBeastsImg1,
  nitroBeastsImg2,
  nitroBeastsImg3,
  nitroMountainImg1,
  nitroMountainImg2,
  nitroMountainImg3,
  rideKinkImg1,
  rideKinkImg2,
  rideKinkImg3,
  rideAlgorithmImg1,
  rideAlgorithmImg2,
  rideAlgorithmImg3,
  backcountryImg1,
  backcountryImg2,
  backcountryImg3,
  romeSlapstickImg1,
  romeSlapstickImg2,
  romeSlapstickImg3,
  romeRoyalImg1,
  romeRoyalImg2,
  romeRoyalImg3,
  romeMuseImg1,
  romeMuseImg2,
  romeMuseImg3,
  roxySmoothieImg1,
  roxySmoothieImg2,
  roxySmoothieImg3,
  roxyDawnImg1,
  roxyDawnImg2,
  roxyDawnImg3,
  drakeMistyImg1,
  drakeMistyImg2,
  drakeMistyImg3,
  drakeCharmImg1,
  drakeCharmImg2,
  drakeCharmImg3,
  drakeSquadImg1,
  drakeSquadImg2,
  drakeSquadImg3,
} from './snowboard-images';

import {
  burtonBoaImg1,
  burtonBoaImg2,
  burtonBoaImg3,
  burtonFelixImg1,
  burtonFelixImg2,
  burtonFelixImg3,
  burtonMotoImg1,
  burtonMotoImg2,
  burtonMotoImg3,
  burtonStepImg1,
  burtonStepImg2,
  burtonStepImg3,
  dcMoraImg1,
  dcMoraImg2,
  dcMoraImg3,
  dcMutinyImg1,
  dcMutinyImg2,
  dcMutinyImg3,
  dcTranscendImg1,
  dcTranscendImg2,
  dcTranscendImg3,
  nitroBiancaImg1,
  nitroBiancaImg2,
  nitroBiancaImg3,
  nitroProfileImg1,
  nitroProfileImg2,
  nitroProfileImg3,
  northwaveDecadeImg1,
  northwaveDecadeImg2,
  northwaveDecadeImg3,
  northwaveDevineImg1,
  northwaveDevineImg2,
  northwaveDevineImg3,
  ttMelanconImg1,
  ttMelanconImg2,
  ttMelanconImg3,
  ttSantaImg1,
  ttSantaImg2,
  ttSantaImg3,
  ttShiftyImg1,
  ttShiftyImg2,
  ttShiftyImg3,
  ttSLashedImg1,
  ttSLashedImg2,
  ttSLashedImg3,
  vansDoneImg1,
  vansDoneImg2,
  vansDoneImg3,
  vansInvadoImg1,
  vansInvadoImg2,
  vansInvadoImg3,
  vansOGImg1,
  vansOGImg2,
  vansOGImg3,
  vansRangeImg1,
  vansRangeImg2,
  vansRangeImg3,
} from './boots-images';
import {
  anonGretaImg1,
  anonGretaImg2,
  anonGretaImg3,
  anonMfiImg1,
  anonMfiImg2,
  anonMfiImg3,
  anonOsloImg1,
  anonOsloImg2,
  anonOsloImg3,
  giroEllaImg1,
  giroEllaImg2,
  giroEllaImg3,
  giroLedgeImg1,
  giroLedgeImg2,
  giroLedgeImg3,
  giroTrigImg1,
  giroTrigImg2,
  giroTrigImg3,
  googleHeavenImg1,
  googleHeavenImg2,
  googleInterImg1,
  googleInterImg2,
  googleInterImg3,
  googleMammothImg1,
  googleMammothImg2,
  googleMammothImg3,
  googleMermaidImg1,
  googleMermaidImg2,
  googleMermaidImg3,
  oakleyFallImg1,
  oakleyFallImg2,
  oakleyFallImg3,
  oakleyFrameImg1,
  oakleyFrameImg2,
  oakleyFrameImg3,
  oakleyProImg1,
  oakleyProImg2,
  oakleyProImg3,
  oakleyTargetImg1,
  oakleyTargetImg2,
  oakleyTargetImg3,
  smithHelmetImg1,
  smithHelmetImg2,
  smithHelmetImg3,
  smithMagImg1,
  smithMagImg2,
  smithMagImg3,
  smithMazeImg1,
  smithMazeImg2,
  smithMazeImg3,
  smithSequenceImg1,
  smithSequenceImg2,
  smithSquadImg1,
  smithSquadImg2,
  sweetInterstellarImg1,
  sweetInterstellarImg2,
  sweetInterstellarImg3,
  sweetProtectionClockImg1,
  sweetProtectionClockImg2,
  sweetProtectionClockImg3,
} from './accessories-images';

const snowBoards: Array<ProductData> = [
  {
    category: 'snowboards',
    brand: 'Burton',
    name: 'Free Thinker Snowboard',
    price: 629,
    rating: 5,
    quantity: 29,
    description:
      'Expand horizons on the Burton Free Thinker Snowboard, an all-mountain machine with a penchant for the park and the ability to surf side-hits. With a true twin shape and a classic camber profile, the Free Thinker delivers excellent control while riding regular or switch, and a mid-stiff profile offers the reactivity we crave for big jumps and tight turns. Burton finished off this board with their speed-demon WFO base and 45° Carbon Highlights for ideal torsional stiffness and extra snap.',
    images: [
      burtonFreeThinkerImg1,
      burtonFreeThinkerImg2,
      burtonFreeThinkerImg3,
    ],
  },
  {
    category: 'snowboards',
    brand: 'Burton',
    name: 'Blossom Snowboard',
    price: 609,
    rating: 4,
    quantity: 120,
    description:
      'The Burton Blossom Snowboard is a perennial choice for riding gardens and groves of groomers and grinders with nothing but flowery flow. In the true twin shape that park-goers love, backed by a tried-and-true camber profile, we can ride away with clear-cut power in either direction when spinning off tubes or slashing down the hill. The Blossom has a clear focus on park and freestyle riding, but its personality offers a happy medium for exploring the entire resort.',
    images: [burtonBlossomImg1, burtonBlossomImg2, burtonBlossomImg3],
  },
  {
    category: 'snowboards',
    brand: 'Burton',
    name: 'Family Tree 3D Daily Driver',
    price: 659,
    rating: 5,
    quantity: 67,
    description:
      'Like the other boards in the Family Tree lineup, the Burton Family Tree 3D Daily Driver Snowboard took inspiration from classic profiles and added pow-friendly, mountain-dominating pizzazz to better our ride. The Daily Driver is just that—an all-mountain profile that rips through the fresh snow in the trees and the neatly groomed runs from green to black. Camber underfoot puts power in our glide, while the 3D-scooped rocker nose floats over both soft and sticky snow. Its directional shape and medium flex creates a surfy feel on any terrain, but its switch-friendly tail does not stick us in one stance.',
    images: [burtonFamilyImg1, burtonFamilyImg2, burtonFamilyImg3],
  },
  {
    category: 'snowboards',
    brand: 'Burton',
    name: 'Custom X',
    price: 839,
    rating: 4.5,
    quantity: 10,
    description:
      "The Burton Custom X brings us lightning-like response and surgical precision to pick apart any zone on the mountain. Its directional shape gives it a hard-charging feel on groomers and helps the board float through powder, yet it rides and lands switch thanks to its twin flex pattern. Pop in the unbelievably light Dragonfly core and Squeezebox High core profiling to help us drive turns and the carbon stringers for that extra horsepower, and we're left with a board that's always prepared to tear up the local resorts.",
    images: [burtonCustomImg1, burtonCustomImg2, burtonCustomImg3],
  },

  {
    category: 'snowboards',
    brand: 'Burton',
    name: 'Instigator Flat Top',
    price: 439,
    rating: 3,
    quantity: 34,
    description:
      "The only fight we're picking with the Burton Instigator Flat Top Snowboard is with ourselves on how to master snowboarding's many facets. With an extremely soft flex, forgiving profile, and smooth flexing balance, the Instigator is ready to take us above and beyond as we figure out how we like to ride the resort.",
    images: [burtonInstigatorImg1, burtonInstigatorImg2, burtonInstigatorImg3],
  },

  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Prime X DD',
    price: 329,
    rating: 3.5,
    quantity: 77,
    description:
      'Progression-driven and catch-free, the Nitro Prime X DD Snowboard is what we strap into for smoothing out the learning curve and having fun all over the resort. The playful medium flex and forgiving Flat-Out Rocker profile bring a comfortable, effortless feel to our feet, while the directional shape and light, responsive core boost confidence for dropping into unknown steeps. We also appreciate that Nitro rounded this smile-inducing ATV deck with a Premium Extruded FH base to withstand the impact that can come along with progressing through varying terrain.',
    images: [nitroPrimeImg1, nitroPrimeImg2, nitroPrimeImg3],
  },
  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Prime Raw',
    price: 329,
    rating: 4,
    quantity: 34,
    description:
      'Progression-driven and catch-free, the Nitro Prime Raw Snowboard is what we strap into for smoothing out the learning curve and having fun all over the resort. The playful medium flex and forgiving Flat-Out Rocker profile bring a comfortable, effortless feel to our feet, while the directional shape and light, responsive core boost confidence for dropping into unknown steeps. We also appreciate that Nitro rounded this smile-inducing ATV deck with a Premium Extruded FH base to withstand the impact that can come along with progressing through varying terrain.',
    images: [nitroPrimeRawImg1, nitroPrimeRawImg2, nitroPrimeRawImg3],
  },
  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Drop Snowboard',
    price: 489,
    rating: 5,
    quantity: 134,
    description:
      "The Drop Snowboard is a versatile directional stick that surfs powder and carves groomers with equal proficiency, ensuring that every day is a good day to ride. The traditional powder shape, Cam-Out hybrid profile, and medium flex make the Drop an easy choice for any day on the mountain, even if fresh snow hasn't fallen. When a storm creeps in overnight, there's no need to swap boards: the directional shape puts our weight over the tail and raises the tip, keeping us afloat. Nitro's unique Power Pods add edge grip for railing turns on hardpack or navigating the steeps, while a lightweight and strong Powercore and Bi-Lite laminates offer lightweight strength and smooth flex. A rock-solid sintered base keeps us blasting downhill at full speed, finishing this board on a confidence-boosting high-note.",
    images: [nitroDropImg1, nitroDropImg2, nitroDropImg3],
  },
  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Cheap Thrills',
    price: 439,
    rating: 3.5,
    quantity: 101,
    description:
      'Built to take a beating when learning the ropes of the parks, the Nitro Cheap Thrills Snowboard is here for us park and rail riders looking for a tough board that can handle the abuse from bashing steel and pushing the envelope. With a medium flex, twin shape, and Flat-Out profile, this deck is prepared to expand our bag of tricks and keep our wallet full for post-shred pizza.',
    images: [nitroCheapImg1, nitroCheapImg2, nitroCheapImg3],
  },
  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Beast',
    price: 649,
    rating: 5,
    quantity: 12,
    description:
      "The Beast Snowboard mixes past, present, and future to create a durable, responsive, and just plain fun board for hot-lapping parks everywhere. The True Camber profile doesn't mess around with any rocker and instead provides a blast-from-the-past with the proven performance of full camber: poppy, responsive, and stable, pretty much everything we could want in a park board. Working with that classic camber profile, a modern true twin shape provides all the control needed, both regular and switch, to confidently try any trick. Finally, futuristic construction attributes like double-wide Railkiller edges, a reinforced Diamond Band, and Ballistic Impact panels ensure longevity from icy early season sessions to late spring slush park shoots.",
    images: [nitroBeastsImg1, nitroBeastsImg2, nitroBeastsImg3],
  },
  {
    category: 'snowboards',
    brand: 'Nitro',
    name: 'Mountain',
    price: 599,
    rating: 5,
    quantity: 7,
    description:
      'We appreciate that the hard-charging Nitro Mountain Snowboard features a slightly tapered shape with narrower rear contact points. This drops our back foot in pow for float and maneuverability while cutting hard carves or weaving through tight trees. The Cam-Out profile mixes powerful camber from just inside contact points with rocker sections towards the tip and tail to enhance float and maneuverability. It also creates powerful energy transfer to the edges for tighter turns and an easier time navigating dicey situations.',
    images: [nitroMountainImg1, nitroMountainImg2, nitroMountainImg3],
  },
  {
    category: 'snowboards',
    brand: 'Ride',
    name: 'Kink Snowboard',
    price: 429,
    rating: 4.5,
    quantity: 21,
    description:
      "From the park to the streets, we're always ready to handle freestyle business with the RIDE Kink Snowboard. This soft-flexing, true twin board is built with a camber-driven profile for a classic freestyle feel. RIDE's Twin Extra Camber combines a large camber section that provides excellent pop and edge control, with short rocker sections out to the tip and tail to help reduce the chance of an edge catch ruining your session. Plus, Double Impact Plates and beefy Cleave Edges ensure that the Kink can take a beating from repeated tricks on rails or landing flat in street environments.",
    images: [rideKinkImg1, rideKinkImg2, rideKinkImg3],
  },
  {
    category: 'snowboards',
    brand: 'Ride',
    name: 'Algorythm Snowboard',
    price: 599,
    rating: 3.5,
    quantity: 57,
    description:
      "We head to the resort with the RIDE Algorythm Snowboard to check all the performance boxes in everything from waist-deep powder to groomer laps across the mountain. This true all-mountain machine features a hybrid rocker profile, directional twin shape, and medium flex for float and forgiveness without missing out on edge hold and pop. A lightweight construction features Ride's Performance Core and carbon array laminates to add strength and response, while a sintered base keeps us from getting stuck in powder or slush.",
    images: [rideAlgorithmImg1, rideAlgorithmImg2, rideAlgorithmImg3],
  },
  {
    category: 'snowboards',
    brand: 'Backcountry',
    name: 'Toby Miller Pro Model',
    price: 550,
    rating: 4.5,
    quantity: 10,
    description:
      "Sure, we could go on and on about all of the amazing design elements and cutting-edge tech that went into the creation of the Toby Miller Pro Snowboard. And yeah, we could wax poetic about Backcountry athlete Toby Miller busting back sevens in the park, or rhapsodize about how effortless and graceful the carves you'll lay down on high-speed groomer runs can be. But, really, we think taking this bad boy up to the resort and strapping in is the best way to find out for yourself just what makes it such an incredible all-mountain ripper. We mean, if Toby Miller has his name on it, is there really anything left to be said?",
    images: [backcountryImg1, backcountryImg2, backcountryImg3],
  },
  {
    category: 'snowboards',
    brand: 'Rome',
    name: 'Slapstick Snowboard ',
    price: 329,
    rating: 3.5,
    quantity: 145,
    description:
      "Rome designed the Slapstick Snowboard for the grom that isn't getting what they need from traditional kids' boards. Standard kids' boards are made with lesser materials because companies don't think the littles shred as hard, but we're happy to say this board bucks that notion. The Slapstick comes with a hybrid camber profile and medium flex to rip big lines in the park and smooth carves on the corduroy. Raised contact points allow for graceful turns on grainy powder laps, and a Stomp Core keeps its weight down so the kids can go big without being held back.",
    images: [romeSlapstickImg1, romeSlapstickImg2, romeSlapstickImg3],
  },
  {
    category: 'snowboards',
    brand: 'Rome',
    name: 'Royal Snowboard',
    price: 399,
    rating: 4,
    quantity: 4,
    description:
      "Rule the resort atop the Rome Royal Snowboard. Its soft flex and flat-rocker profile are easy to dominate whether we've been exploring this mountain for seasons or strapping into a board for the first time. Rockered tips prevent catching, while the flat camber between the bindings allows us to hold and edge as we carve downhill. And while its soft flex means more forgiving maneuvers, this board doesn't sacrifice strength—a full-poplar Stomp core with Bamboo HotRods in each tip give it the power to hit park features and ollie along our favorite runs.",
    images: [romeRoyalImg1, romeRoyalImg2, romeRoyalImg3],
  },
  {
    category: 'snowboards',
    brand: 'Rome',
    name: 'Muse Snowboard',
    price: 499,
    rating: 5,
    quantity: 27,
    description:
      "Snowboarding is an art, and the Rome Muse Snowboard is our inspiration to creating mountain masterpieces. Rome's philosophy for this board is agility with a fluid design that hits the mark. The medium flex, narrow waist width, and versatile Fusion Camber profile provide us the ultimate level of control for ripping imaginative lines across every trail at the resort. The directional twin shape and slightly firmer medium flex keeps us in the driver's seat in powdery and choppy conditions alike. Plus, the poppy Stomp Core backed with bamboo HotRods helps us boost sidehits and park jumps higher and further than ever before.",
    images: [romeMuseImg1, romeMuseImg2, romeMuseImg3],
  },
  {
    category: 'snowboards',
    brand: 'Roxy',
    name: 'Smoothie Snowboard',
    price: 479,
    rating: 3,
    quantity: 51,
    description:
      'The Roxy team-influenced Smoothie Snowboard is one of the most versatile rides in their lineup. The signature C2 profile and playful mid-flex keep the board lively on park and groomer laps. The directional shape encourages exploring off-piste, and Magne-Traction lets us keep our grip no matter the terrain.',
    images: [roxySmoothieImg1, roxySmoothieImg2, roxySmoothieImg3],
  },
  {
    category: 'snowboards',
    brand: 'Roxy',
    name: 'Dawn Snowboard',
    price: 349,
    rating: 5,
    quantity: 5,
    description:
      'While our friends on the hill are hyped to ride first chair to last, we keep up on the Roxy Dawn Snowboard. This beginner-friendly deck features a soft flex, a forgiving rocker profile, and reliable Magne-Traction edge tech so we can run through laps without feeling the fatigue. Catch-free rockered tips keep us upright, and the serrated board edges keep us from washing out.',
    images: [roxyDawnImg1, roxyDawnImg2, roxyDawnImg3],
  },
  {
    category: 'snowboards',
    brand: 'Drake',
    name: 'Misty Snowboard',
    price: 469,
    rating: 4.5,
    quantity: 11,
    description:
      "From the park to the streets, we're always ready to handle freestyle business with the Drake Misty Snowboard. This soft-flexing, true twin board is built with a camber-driven profile for a classic freestyle feel. RIDE's Twin Extra Camber combines a large camber section that provides excellent pop and edge control, with short rocker sections out to the tip and tail to help reduce the chance of an edge catch ruining your session. Plus, Double Impact Plates and beefy Cleave Edges ensure that the Kink can take a beating from repeated tricks on rails or landing flat in street environments.",
    images: [drakeMistyImg1, drakeMistyImg2, drakeMistyImg3],
  },
  {
    category: 'snowboards',
    brand: 'Drake',
    name: 'Charm Snowboard',
    price: 379,
    rating: 3,
    quantity: 8,
    description:
      "From the park to the streets, we're always ready to handle freestyle business with the Drake Charm Snowboard. This soft-flexing, true twin board is built with a camber-driven profile for a classic freestyle feel. RIDE's Twin Extra Camber combines a large camber section that provides excellent pop and edge control, with short rocker sections out to the tip and tail to help reduce the chance of an edge catch ruining your session. Plus, Double Impact Plates and beefy Cleave Edges ensure that the Kink can take a beating from repeated tricks on rails or landing flat in street environments.",
    images: [drakeCharmImg1, drakeCharmImg2, drakeCharmImg3],
  },
  {
    category: 'snowboards',
    brand: 'Drake',
    name: 'Squad Snowboard',
    price: 469,
    rating: 4,
    quantity: 36,
    description:
      "From the park to the streets, we're always ready to handle freestyle business with the Drake Squad Snowboard. This soft-flexing, true twin board is built with a camber-driven profile for a classic freestyle feel. RIDE's Twin Extra Camber combines a large camber section that provides excellent pop and edge control, with short rocker sections out to the tip and tail to help reduce the chance of an edge catch ruining your session. Plus, Double Impact Plates and beefy Cleave Edges ensure that the Kink can take a beating from repeated tricks on rails or landing flat in street environments.",
    images: [drakeSquadImg1, drakeSquadImg2, drakeSquadImg3],
  },
];

const boots: Array<ProductData> = [
  {
    category: 'boots',
    brand: 'ThirtyTwo',
    name: 'Shifty BOA Snowboard Boot',
    price: 239,
    rating: 5,
    quantity: 45,
    description:
      "ThirtyTwo made the Shifty BOA Snowboard Boot for general all-around comfort on the mountain. Its super-soft flex gives the new rider a forgiving performance and the jaded boarder a 'lax ride. The BOA Fit SYstem gets the boots on fast, keeps them tight, and lets us shed them quickly after long days. The Evolution Foam midsole is the cherry on top, giving us optimal cush below and keeping us going lap after lap.",
    images: [ttShiftyImg1, ttShiftyImg2, ttShiftyImg3],
    sizes: [5, 6, 7, 8, 9, 12],
  },
  {
    category: 'boots',
    brand: 'ThirtyTwo',
    name: 'Lashed Double BOA Powell',
    price: 349,
    rating: 4.5,
    quantity: 12,
    description:
      'The ThirtyTwo Lashed Double BOA Powell Snowboard Boot delivers all-mountain comfort and performance in a vibrant package. We love being able to dial in our perfect fit with the dual-zone BOA® fit system, and the Team Fit liner is heat-moldable for a completely customized fit. The versatile medium flex excels from park to pow and everything in between.',
    images: [ttSLashedImg1, ttSLashedImg2, ttSLashedImg3],
    sizes: [6, 7, 9, 12],
  },
  {
    category: 'boots',
    brand: 'ThirtyTwo',
    name: 'Lashed Double BOA Melancon',
    price: 359,
    rating: 5,
    quantity: 17,
    description:
      'The ThirtyTwo Lashed Double BOA Melancon Snowboard Boot delivers unmatched comfort, support, and durability to help reach our goal of a 100-day season. Its evolution foam cushioning and Team Fit liner with dual-density intuition foam provide medium support and flex and can be heat-molded for an even more perfect fit. The molded footbed features a heel cradle and excellent arch support, while our feet stay locked in and secure with the dual BOA closure system and TX3 laces.',
    images: [ttMelanconImg1, ttMelanconImg2, ttMelanconImg3],
    sizes: [5, 6, 7, 9, 11],
  },
  {
    category: 'boots',
    brand: 'ThirtyTwo',
    name: 'Lashed Double BOA Santa Cruz',
    price: 349,
    rating: 5,
    quantity: 9,
    description:
      "We like ThirtyTwo's Lashed Double BOA Santa Cruz Snowboard Boot for its reliable support and comfort that keeps us on the mountain for a full day of hitting new tricks and finding fresh powder. Constructed with dual-density intuition foam, a 3D molded tongue, and a performance backstay, we are provided with a boot that is so comfortable we won't even know we are wearing it. To ensure a secure fit and easy on-the-go adjustments, ThirtyTwo incorporated the Dual BOA closure system with TX3 lace.",
    images: [ttSantaImg1, ttSantaImg2, ttSantaImg3],
    sizes: [6, 7, 8, 9],
  },
  {
    category: 'boots',
    brand: 'Burton',
    name: 'Photon Step On Snowboard Boot',
    price: 459,
    rating: 4,
    quantity: 54,
    description:
      "Even without straps, we can ride hard in the Photon Step On Snowboard Boot. One of Burton's most popular styles joins the Step On community and receives a few updates in this winter's edition. An S4 foam panel at the sides enhances comfort and cuts weight for faster charging and higher flying, and the over-foot strap offers a greater locked-in feel while riding binding-strap-free. Without traditional bindings, the Photon Step On still delivers the precision, responsiveness, and comfort this mid-stiff ride is known for.",
    images: [burtonStepImg1, burtonStepImg2, burtonStepImg3],
    sizes: [5, 8, 11],
  },
  {
    category: 'boots',
    brand: 'Burton',
    name: 'Ruler BOA Snowboard Boot',
    price: 329,
    rating: 4,
    quantity: 19,
    description:
      "We're leading our own lifestyle at the resort when we choose to cruise in the Burton Ruler BOA Snowboard Boot. Built for comfort and ease of use, Burton's Ruler features an Imprint 2 liner and BOA Fit System to softly wrap our feet with a secure fit and dialed response. The special liner comes at a meager weight so that we don't feel like we're in waders, and it ensures we're warm, dry, and ready to ride.",
    images: [burtonBoaImg1, burtonBoaImg2, burtonBoaImg3],
    sizes: [7, 8, 9],
  },
  {
    category: 'boots',
    brand: 'Burton',
    name: 'Felix BOA Snowboard Boot',
    price: 419,
    rating: 5,
    quantity: 27,
    description:
      "Where cozy comfort and performance collide, the Burton Felix BOA Snowboard Boot is born and ready to take on the varied runs at our favorite resorts. High-end features like the Dual Zone BOA Fit System lacing and top-tier Imprint 3 liner keep us locked in with a mid-stiff flex that charges in freeride terrain and loosens up enough for the park. After functional tech comes comfort, and Burton didn't cut back. The Plush Cuff creates a snug fit on the calf and features a furry lining for maximum coziness. The Focus Cuff reduces heel lift on fast turns and bootpacks. And the DryRide Heat Cycle lining reflects our feet's heat while also wicking chilly moisture, so our feet don't feel frigid on active or icy days.",
    images: [burtonFelixImg1, burtonFelixImg2, burtonFelixImg3],
    sizes: [5, 6, 7, 8, 10],
  },
  {
    category: 'boots',
    brand: 'Burton',
    name: 'Moto BOA Snowboard Boot',
    price: 249,
    rating: 3,
    quantity: 13,
    description:
      "Before dominating the hill comes dialing in skills, and there's no better way than in the dialed-in fit of the Burton Moto BOA Snowboard Boot. This soft-flexing boot delivers forgiveness and comfort that lets learners stay on their feet and build snowboarding foundations, so they can rip black diamonds in no time.",
    images: [burtonMotoImg1, burtonMotoImg2, burtonMotoImg3],
    sizes: [10, 12],
  },
  {
    category: 'boots',
    brand: 'Vans',
    name: 'Hi-Standard OG Snowboard Boot',
    price: 199,
    rating: 3,
    quantity: 92,
    description:
      'With over two decades on the market, the Vans Hi-Standard OG Snowboard Boots are still leading the way for comfort and freestyle performance. The go-to boots for many Vans pro riders, the Hi-Standard OGs have a lightweight design and medium flex to help us excel in the park and dominate the streets. The traditional lacing system features double-posted gripping lace hooks that prevent the laces from slipping, so your boots stay tight from first run to last.',
    images: [vansOGImg1, vansOGImg2, vansOGImg3],
    sizes: [5, 8, 10, 12],
  },
  {
    category: 'boots',
    brand: 'Vans',
    name: 'Invado Pro Snowboard Boot',
    price: 269,
    rating: 4,
    quantity: 76,
    description:
      "The Invado Pro Snowboard Boot is just the ticket we need for boarding the resort with a feel we can't find anywhere else. Two things make this boot unique: one is the Boa and Lace closure which dials in a tight fit that's sure to help while lapping the rail garden rope tow. The other is the merino wool liner that helps keep our feet dry, less smelly, and at just the right temperature. Add in the versatile medium flex and we find ourselves with just about all we could ask for in an all-mountain boot.",
    images: [vansInvadoImg1, vansInvadoImg2, vansInvadoImg3],
    sizes: [7, 8, 10],
  },
  {
    category: 'boots',
    brand: 'Vans',
    name: 'Verse Range Edition Snowboard Boot',
    price: 499,
    rating: 5,
    quantity: 6,
    description:
      "Just when we thought a boot couldn't be more backcountry-ready, Vans upped the ante with their Verse Range Edition Snowboard Boot. This out-of-bounds offering features all the flex-changing uphill-downhill tech of the classic Verse with an added Drop-Cuff that unlocks, widens the cuff, and expands our range of motion for bootpacking and skinning. Boa Custom Focus Plus, Vans' Custom Slide Guide, and a Powercuff strap lock in the ideal fit while maintaining hike-ready ankle flexibility and superior heel hold. Breathable valves, a waterproof zipper shroud, and The North Face's FlashDry technology loaded into the liner keep feet moisture-free no matter how much snow or sweat we encounter on our climb.",
    images: [vansRangeImg1, vansRangeImg2, vansRangeImg3],
    sizes: [10, 11, 12],
  },
  {
    category: 'boots',
    brand: 'Vans',
    name: 'One & Done/Hana Beaman Snowboard Boot',
    price: 319,
    rating: 5,
    quantity: 31,
    description:
      "Inspired by the career of the rider it's named after, the Vans One & Done/Hana Beaman Snowboard boot reflects the idea of progressing to the next level, helping us search out big-mountain lines in more remote locations in confidence. A medium-stiff flex works in tandem with the V3 UltraCush liner and V3 harness for increased stability and support when we're staring down technical chutes, while the hybrid BOA Fit System guarantees an exact fit in seconds. We especially appreciate the V3 Superenduro Waffle outsole with All-Trac Rubber giving us the grippy power of multi-directional treads, surface-level texturing, and a TPU toe pick for firm footing in the dicey, no-fall zones.",
    images: [vansDoneImg1, vansDoneImg2, vansDoneImg3],
    sizes: [5, 7, 9, 11],
  },
  {
    category: 'boots',
    brand: 'DC',
    name: 'Mora Snowboard Boot',
    price: 329,
    rating: 4,
    quantity: 42,
    description:
      "We go right from high-flying park laps to hard-charging powder runs with the mid-stiff flex and dual-zone tightening of the DC Mora Boa Snowboard Boots. Tightening over the upper and lower zones independently with the simple twist of a reel, the H4 Boa Coiler closure system dials in a truly custom fit to your unique riding style, as well as the specific terrain at hand. Keep the lower a bit looser during those park laps and jib sessions or tighten both zones for the utmost in response when you're bombing steeps and dropping cliffs. Either way, it's all yours to control at a moment's notice. Plus, we love that the zippered Stormproof StormFlap keeps snow out of your boot for added warmth and weather protection.",
    images: [dcMoraImg1, dcMoraImg2, dcMoraImg3],
    sizes: [10, 11, 12],
  },
  {
    category: 'boots',
    brand: 'DC',
    name: 'Transcend Snowboard Boot',
    price: 399,
    rating: 5,
    quantity: 31,
    description:
      "Designed with a focus on all-mountain performance and classic DC style, the Transcend Boot takes us from pow to peak to park with stiff response and tons of comfort. The responsive R3 liner keeps our control twitchy-fast and adds support for big drops and high-speed chop runs, while the 3M Thinsulate insulation ensures toasty toes on those slow, frigid lift rides. The Boa Fit System securely tightens down the perfect fit in seconds, with independent zones allowing for customized performance, while the eco-friendly IMPACT-ALG insole boosts both comfort and the boot's heel hold. Rounding things out with a Vibram outsole, DC really made sure all the boxes got checked off when creating this all-mountain powerhouse.",
    images: [dcTranscendImg1, dcTranscendImg2, dcTranscendImg3],
    sizes: [10, 12],
  },
  {
    category: 'boots',
    brand: 'DC',
    name: 'Mutiny Snowboard Boot',
    price: 250,
    rating: 4,
    quantity: 33,
    description:
      'Featuring a versatile freestyle feel and a skate-inspired design, the Mutiny Snowboard Boot is the one to count on when we bring our tricks to massive urban rails and backcountry booters. Its medium flex is supportive enough to take on jumps and big drops but still allows us to get loose on jibs and flow around the resort. Memory foam in the Response II liner offers out-of-the-box warmth and comfort, and heat-moldable EVA creates a custom fit over time. The lightweight and cushy Unilite outsole is beefed-up with rubber panels in strategic areas that add durability and improve traction on icy streets and exposed ridgelines.',
    images: [dcMutinyImg1, dcMutinyImg2, dcMutinyImg3],
    sizes: [7, 8, 9, 10],
  },
  {
    category: 'boots',
    brand: 'Nitro',
    name: 'Profile TLS Step On Snowboard Boot',
    price: 429,
    rating: 4,
    quantity: 19,
    description:
      'Built for use with Burton Step On bindings, The Nitro Profile TLS Step On Snowboard Boot provides comfort and convenience for full days on the mountain. Its zonal Twin Lacing System allows quick and effortless boot removal and features low-abrasion Dyneema laces for long-lasting use. At the same time, the innovative Re/Lace Liner Locker lets us make quick adjustments without removing our boot, and to find our perfect stiffness level, we use the power tongue stiffener to switch between a stiff or relaxed fit.',
    images: [nitroProfileImg1, nitroProfileImg2, nitroProfileImg3],
    sizes: [7, 8, 11],
  },
  {
    category: 'boots',
    brand: 'Nitro',
    name: 'Bianca TLS Snowboard Boot',
    price: 479,
    rating: 5,
    quantity: 41,
    description:
      "The Bianca TLS Snowboard Boots include Nitro's top technologies to provide us with unmatched comfort and response all over the mountain. Featuring a medium-stiff flex, the Bianca offers support for navigating natural terrain or hitting the biggest parks at the resort.  An air dampening pocket and a triple-density Ortholite footbed work together to absorb harsh impacts from big landings or variable snow, and the Vibram Icetrek and Arctic Grip sole gives us supreme traction for bootpacking up to the peak.",
    images: [nitroBiancaImg1, nitroBiancaImg2, nitroBiancaImg3],
    sizes: [10, 11, 12],
  },
  {
    category: 'boots',
    brand: 'Northwave Snow',
    name: 'Decade Pro Snowboard Boot',
    price: 329,
    rating: 4,
    quantity: 27,
    description:
      "The Decade Pro Snowboard Boots include Northwave Snow's top technologies to provide us with unmatched comfort and response all over the mountain. Featuring a medium-stiff flex, the Bianca offers support for navigating natural terrain or hitting the biggest parks at the resort.  An air dampening pocket and a triple-density Ortholite footbed work together to absorb harsh impacts from big landings or variable snow, and the Vibram Icetrek and Arctic Grip sole gives us supreme traction for bootpacking up to the peak.",
    images: [northwaveDecadeImg1, northwaveDecadeImg2, northwaveDecadeImg3],
    sizes: [9, 10],
  },
  {
    category: 'boots',
    brand: 'Northwave Snow',
    name: 'Devine Hybrid Snowboard Boot',
    price: 339,
    rating: 5,
    quantity: 1,
    description:
      "The Devine Hybrid Snowboard Boots include Northwave Snow's top technologies to provide us with unmatched comfort and response all over the mountain. Featuring a medium-stiff flex, the Bianca offers support for navigating natural terrain or hitting the biggest parks at the resort.  An air dampening pocket and a triple-density Ortholite footbed work together to absorb harsh impacts from big landings or variable snow, and the Vibram Icetrek and Arctic Grip sole gives us supreme traction for bootpacking up to the peak.",
    images: [northwaveDevineImg1, northwaveDevineImg2, northwaveDevineImg3],
    sizes: [5, 6, 7, 8, 9],
  },
];

const accessories: Array<ProductData> = [
  {
    category: 'accessories',
    brand: 'Smith',
    name: 'Code MIPS Helmet',
    price: 120,
    rating: 3.5,
    quantity: 29,
    description:
      "Featuring a low-profile in-mold design, the Code doesn't skimp on durability while creating a lightweight product. The polycarbonate shell and EPS liner bring us a high level of protection, with an incorporated Koroyd material that aids in impact absorption as well as airflow. The MIPS System uses slip-plane technology, reducing rotational force common in angular impacts, while tons of ventilation regulates airflow to keep us from overheating.",
    images: [smithHelmetImg1, smithHelmetImg2, smithHelmetImg3],
  },
  {
    category: 'accessories',
    brand: 'Smith',
    name: 'Squad S Goggles',
    price: 120,
    rating: 4,
    quantity: 12,
    description:
      'For a great fit and view, we kit up with the Smith Squad S Goggles. We get that made-for-us feel with the soft foam and responsive frame molding to our face. The semi-rimless design and oversized cylindrical lens give us an unobstructed view of the mountain, while the color- and contrast-enhancing ChromaPop tech ensures we see every variation in the terrain.',
    images: [smithSquadImg1, smithSquadImg2],
  },
  {
    category: 'accessories',
    brand: 'Smith',
    name: 'Maze MIPS Helmet',
    price: 155,
    rating: 5,
    quantity: 29,
    description:
      'One of the lightest snow helmets available, the Smith Maze MIPS Helmet brings us the same ultra-light feel and minimalist look as the original, but with an added safety system to improve protection. The Multi-directional Impact Protection System helps reduce rotational forces in the event of an impact, while the In-Mold construction cuts weight and bulk without compromising protection. Plus, the nine fixed vents and AirEvac system let us keep cool on warm spring days and intense hikes, and the self-adjusting fit system offers a comfy, secure fit.',
    images: [smithMazeImg1, smithMazeImg2, smithMazeImg3],
  },
  {
    category: 'accessories',
    brand: 'Smith',
    name: 'Sequence OTG Goggles',
    price: 130,
    rating: 4,
    quantity: 22,
    description:
      "The Sequence OTG Goggles provide a comfy, over-the-glasses fit and a contrast-enhancing, color-popping visual experience thanks to Smith's coveted ChromaPop technology. These mid-sized goggles offer a helmet-compatible, pressure-free fit that lets our glasses sit comfortably, while fog- and distortion-free lenses give us razor-sharp optics on the mountain.",
    images: [smithSequenceImg1, smithSequenceImg2],
  },
  {
    category: 'accessories',
    brand: 'Smith',
    name: 'I/O MAG XL Low Bridge Fit Goggles',
    price: 270,
    rating: 5,
    quantity: 3,
    description:
      'When the snow is dumping out of the ski we trust the Smith I/O MAG XL Low Bridge Fit Goggles to keep us seeing clearly. The spherical lens limits distortion, the ChromaPop lenses boost contrast in flat light, and the Low Bridge design fits snuggly on high cheekbones to keep air out.',
    images: [smithMagImg1, smithMagImg2, smithMagImg3],
  },
  {
    category: 'accessories',
    brand: 'Anon',
    name: 'Greta 3 Helmet',
    price: 83,
    rating: 5,
    quantity: 22,
    description:
      "Protect your most valuable asset when you're charging the park and ripping steep upper-mountain lines with the Anon Greta Helmet. Featuring Endura hardshell construction, the Greta Helmet fortifies your head from the hard knocks and everyday spills you're bound to encounter over multiple seasons of riding. Passive ventilation along the front and top allows built-up heat to escape on warmer spring days, so you won't succumb to overheating issues. It comes with a classic fleece liner and ear pads for fuzzy-soft comfort, and it's compatible with various audio systems for seamlessly jamming out on the mountain. Meanwhile, the Auto-Adjust fit system ensures a snug, secure, and comfortable fit as you rip down your favorite hill.",
    images: [anonGretaImg1, anonGretaImg2, anonGretaImg3],
  },
  {
    category: 'accessories',
    brand: 'Anon',
    name: 'Oslo WaveCel Helmet',
    price: 219,
    rating: 5,
    quantity: 14,
    description:
      "With clean style and the latest impact protection, the Oslo WaveCel Helmet is a must for on-mountain adventures. Anon's WaveCel technology redistributes impact energy to reduce direct and divert rotational forces. Its breathable design partners with the helmet's passive ventilation channels and moisture-wicking fleece lining to keep us cool while we explore the hill. With a Boa fit system and Fidlock SNAP buckle, we can adjust the helmet's security on-the-fly without our gloves getting in the way.",
    images: [anonOsloImg1, anonOsloImg2, anonOsloImg3],
  },
  {
    category: 'accessories',
    brand: 'Anon',
    name: 'M4S MFI Toric Goggles',
    price: 320,
    rating: 5,
    quantity: 39,
    description:
      "The Anon M4S MFI Toric Goggles help us see bumps and trees on the hill, so we can ski or ride to our full potential. These goggles boast a medium frame size with spherical lenses for enhanced peripheral vision, magnetic lens change technology that lets us keep up with changing conditions, and Anon's Perceive lens tech for clear, high-contrast vision. In addition to Anon's Magne-Tech magnetic lens swapping, MFI technology keeps the compatible face mask locked in with seamless magnets.",
    images: [anonMfiImg1, anonMfiImg2, anonMfiImg3],
  },
  {
    category: 'accessories',
    brand: 'Sweet Protection',
    name: 'Clockwork MAX RIG Reflect BLI Goggles',
    price: 189,
    rating: 4,
    quantity: 14,
    description:
      'Protection doesn’t end with your helmet, your windows to the world need a shield of their own, and the Clockwork MAX RIG make a strong case with a 2,8mm thick Toric sculpted lens that cuts through harsh rays on the snow. GORE Protective Ventilation equalizes pressure while you ski or ride, so your vision stays crystal clear. This BLI model feature a low profile fit for riders with low nose bridge.',
    images: [
      sweetProtectionClockImg1,
      sweetProtectionClockImg2,
      sweetProtectionClockImg3,
    ],
  },
  {
    category: 'accessories',
    brand: 'Sweet Protection',
    name: 'Interstellar RIG Reflect Goggles Replacement Lens',
    price: 150,
    rating: 5,
    quantity: 61,
    description:
      'Protection doesn’t end with your helmet, your windows to the world need a shield of their own, and the Interstellar RIG Reflect Goggles Replacement Lens make a strong case with a 2,8mm thick Toric sculpted lens that cuts through harsh rays on the snow. GORE Protective Ventilation equalizes pressure while you ski or ride, so your vision stays crystal clear. This BLI model feature a low profile fit for riders with low nose bridge.',
    images: [
      sweetInterstellarImg1,
      sweetInterstellarImg2,
      sweetInterstellarImg3,
    ],
  },
  {
    category: 'accessories',
    brand: 'Giro',
    name: 'Ledge MIPS Helmet',
    price: 104,
    rating: 3,
    quantity: 3,
    description:
      'Be it park laps or throwing tricks, the Ledge MIPS Helmet protects us from impact should we take a spill. This helmet offers a snug fit with removable ear pads, ventilation, and audio compatibility so we can listen to our jam band of choice while grooving on groomers.',
    images: [giroLedgeImg1, giroLedgeImg2, giroLedgeImg3],
  },
  {
    category: 'accessories',
    brand: 'Giro',
    name: 'Ella Goggles',
    price: 189,
    rating: 4,
    quantity: 31,
    description:
      'From the towering peaks of British Columbia to the forested glades of Vermont, the Giro Ella Goggle delivers a female-specific fit, unobstructed field of view, and quick-change lens system for rapidly adjusting to conditions. The Ella offers a new-school take on classic cylindrical design, with Expansion View Technology for an unobstructed field of vision. The quick-change lens system features four snap pins and self-locating magnets, so you can quickly pop off the lens and snap in another without prying excessively. Two included lenses allow you to quickly adjust to changing alpine conditions. Both are Vivid lenses by Zeiss, ensuring optical clarity and conditions-specific tint. One lens is suited for all-around lighting and sunnier days, whereas the other is perfect for low-light and stormy days where flat lighting makes skiing difficult.',
    images: [giroEllaImg1, giroEllaImg2, giroEllaImg3],
  },
  {
    category: 'accessories',
    brand: 'Giro',
    name: 'Trig MIPS Helmet',
    price: 160,
    rating: 4,
    quantity: 9,
    description:
      'Freeride skiing and riding is best done with a little extra coverage, and the Giro Trig MIPS Helmet is here to give it to you. It packs in protection against hard knocks, so you can hit the snow with peace of mind, push a little harder in the park, or dive further into the backcountry with confidence.',
    images: [giroTrigImg1, giroTrigImg2, giroTrigImg3],
  },
  {
    category: 'accessories',
    brand: 'Oakley',
    name: 'Mod 1 Pro Helmet',
    price: 150,
    rating: 5,
    quantity: 7,
    description:
      'In creating the Mod 1 Pro Helmet, Oakley kept the clean, skate-style profile of the original Mod 1 Helmet and cranked up its toughness with an injection-molded Dura-Matter Shell over an EPS foam liner to help us ride both in style and with some peace of mind in the protection department. This new and improved Dura-Matter shell brings us the highest level of dent-resistance Oakley has to offer, while the Boa 360 Fit System ensures we can dial in an exact fit every time we strap in. Plus, we count on the fixed venting system to help us cool down on the lift ride quickly after a demanding ride down.',
    images: [oakleyProImg1, oakleyProImg2, oakleyProImg3],
  },
  {
    category: 'accessories',
    brand: 'Oakley',
    name: 'Target Line M Goggles',
    price: 83,
    rating: 3.5,
    quantity: 31,
    description:
      "Winds might be whipping snow all along the ridge, but we can see clearly in Oakley's Target Line M Goggles. Even after we're sweating from hiking up the mountain, the Target Line's anti-fog coating ensures fog-free vision. We also appreciate the strap's helmet-compatible adjustability mixed with a cushy face foam that feels secure whether we're playing it safe or rocking a beanie.",
    images: [oakleyTargetImg1, oakleyTargetImg2, oakleyTargetImg3],
  },
  {
    category: 'accessories',
    brand: 'Oakley',
    name: 'Fall Line XM Prizm Goggles',
    price: 189,
    rating: 5,
    quantity: 51,
    description:
      "Taking the Fall Line refers to taking the most directly downhill path down the mountain, which is why the Oakley Fall Line XM Prizm Goggles will be the perfect addition to your hard-charging runs down steep cruisers. Their Prizm lens technology enhances both contrast visual clarity to help you identify changes in snow conditions so you can react to them faster when you're sailing down the slopes. Their wide, cylindrical lens gives you a large field of vision for better downhill safety, while anti-fog coating ensures that you won't have to deal with cloudy vision when you're working hard. With a flexible frame and moisture-wicking face-foam these goggles will sit comfortably on your face, and thanks to Oakley's Ridgelock lens change system you can quickly and securely swap out a different lens in changing light conditions.",
    images: [oakleyFallImg1, oakleyFallImg2, oakleyFallImg3],
  },
  {
    category: 'accessories',
    brand: 'Oakley',
    name: 'O Frame 2.0 Pro XL Goggles',
    price: 61,
    rating: 3,
    quantity: 20,
    description:
      'For a larger fit that still looks sleek, we pull on the O Frame 2.0 Pro XL. The flexible frame hugs our face seamlessly, even on especially frigid days, while its low-profile build increases our field of view. With dual vents, an anti-fog coating, and a moisture-wicking lining, these goggles keep our window lucid.',
    images: [oakleyFrameImg1, oakleyFrameImg2, oakleyFrameImg3],
  },
  {
    category: 'accessories',
    brand: 'GoogleSoc',
    name: 'Interconnection Soc Lens Cover',
    price: 15,
    rating: 3.5,
    quantity: 2,
    description:
      'Really cool and funny case for your goggles! Made from rPET (recycled polyethylene terephthalate). Surprise your friends and family with your choice of GoogleSoc case :)',
    images: [googleInterImg1, googleInterImg2, googleInterImg3],
  },
  {
    category: 'accessories',
    brand: 'GoogleSoc',
    name: 'Mammoth Soc',
    price: 15,
    rating: 5,
    quantity: 10,
    description:
      'Really cool and funny case for your goggles! Made from rPET (recycled polyethylene terephthalate). Surprise your friends and family with your choice of GoogleSoc case :)',
    images: [googleMammothImg1, googleMammothImg2, googleMammothImg3],
  },
  {
    category: 'accessories',
    brand: 'GoogleSoc',
    name: '7th Heaven Soc',
    price: 15,
    rating: 5,
    quantity: 29,
    description:
      'Really cool and funny case for your goggles! Made from rPET (recycled' +
      ' polyethylene terephthalate). Surprise your friends and family with your choice of GoogleSoc case :)',
    images: [googleHeavenImg1, googleHeavenImg2],
  },
  {
    category: 'accessories',
    brand: 'GoogleSoc',
    name: 'Mermaid Soc',
    price: 15,
    rating: 5,
    quantity: 78,
    description:
      'Really cool and funny case for your goggles! Made from rPET (recycled' +
      ' polyethylene terephthalate). Surprise your friends and family with your choice of GoogleSoc case :)',
    images: [googleMermaidImg1, googleMermaidImg2, googleMermaidImg3],
  },
];

export const dataBase: Array<ProductData> = [
  ...snowBoards,
  ...boots,
  ...accessories,
];
